export const products = [
  { name: 'Tasty Snacks', price: '$8', category: 'Snacks', rating: 4.5, reviewCount: 120, image: 'https://picsum.photos/seed/snacks/400/400', color: 'bg-yellow-50', description: 'Crunchy and delicious snacks perfect for any time of the day. Made with natural ingredients.', weight: '200g' },
  { name: 'Quality Meat', price: '$12', category: 'Meat', rating: 4.8, reviewCount: 85, image: 'https://picsum.photos/seed/meat/400/400', color: 'bg-red-50', description: 'Premium cuts of fresh meat, sourced from local farms. High in protein and flavor.', weight: '500g' },
  { name: 'Garden Fresh', price: '$56', category: 'Vegetables', rating: 4.2, reviewCount: 210, image: 'https://picsum.photos/seed/veggies/400/400', color: 'bg-green-50', description: 'Freshly picked vegetables from our organic gardens. Packed with nutrients and vitamins.', weight: '1 kg' },
  { name: 'Sweet Bakery', price: '$22', category: 'Bakery', rating: 4.6, reviewCount: 150, image: 'https://picsum.photos/seed/bakery/400/400', color: 'bg-orange-50', description: 'Freshly baked breads and pastries. Warm, soft, and absolutely delicious.', weight: '400g' },
  { name: 'Fresh Seafood', price: '$30', category: 'Seafood', rating: 4.4, reviewCount: 64, image: 'https://picsum.photos/seed/seafood/400/400', color: 'bg-slate-50', description: 'Catch of the day! Fresh seafood delivered daily from the coast.', weight: '1 kg' },
  { name: 'Fresh & Juicy', price: '$13', category: 'Fruits', rating: 4.9, reviewCount: 320, image: 'https://picsum.photos/seed/fruits/400/400', color: 'bg-purple-50', description: 'Sweet and juicy seasonal fruits. Perfect for a healthy snack or dessert.', weight: '500g' },
  { name: 'Organic Milk', price: '$5', category: 'Dairy', rating: 4.7, reviewCount: 412, image: 'https://picsum.photos/seed/milk/400/400', color: 'bg-blue-50', description: 'Pure organic milk from grass-fed cows. Rich in calcium and vitamins.', weight: '1 L' },
  { name: 'Whole Grain Bread', price: '$4', category: 'Bakery', rating: 4.3, reviewCount: 189, image: 'https://picsum.photos/seed/bread/400/400', color: 'bg-amber-50', description: 'Healthy whole grain bread, baked fresh daily. High in fiber and nutrients.', weight: '400g' },
  { name: 'Green Tea', price: '$15', category: 'Beverages', rating: 4.6, reviewCount: 245, image: 'https://picsum.photos/seed/tea/400/400', color: 'bg-emerald-50', description: 'Refreshing green tea leaves. Rich in antioxidants and perfect for a calm moment.', weight: '100g' },
  { name: 'Dark Chocolate', price: '$7', category: 'Snacks', rating: 4.8, reviewCount: 567, image: 'https://picsum.photos/seed/chocolate/400/400', color: 'bg-stone-50', description: 'Rich dark chocolate with 70% cocoa. A decadent treat for chocolate lovers.', weight: '100g' },
  { name: 'Greek Yogurt', price: '$6', category: 'Dairy', rating: 4.5, reviewCount: 134, image: 'https://picsum.photos/seed/yogurt/400/400', color: 'bg-indigo-50', description: 'Thick and creamy Greek yogurt. High in protein and great with honey or fruit.', weight: '200g' },
  { name: 'Fresh Pasta', price: '$9', category: 'Pantry', rating: 4.4, reviewCount: 92, image: 'https://picsum.photos/seed/pasta/400/400', color: 'bg-rose-50', description: 'Authentic fresh pasta made with durum wheat. Cooks in minutes for a perfect meal.', weight: '500g' },
];

export const filterCategories = ['All', 'Fruits', 'Vegetables', 'Snacks', 'Bakery'];
